spring.application.name=backend

app.frontend.url=http://localhost:4200

jwt.secret=AfTz6L1nK9sW8mP6rJvXqT7eUc1ZHa0OqWdGM7yVn2FjP4lXkS2rZb1cN4hW5e9A
jwt.token.access.expire.time=600000
jwt.token.refresh.expire.time=604800000

spring.datasource.username=neondb_owner
spring.datasource.password=npg_wqjo6ngS9WPO
spring.datasource.url=jdbc:postgresql://ep-wandering-frost-azwev19u.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=aashishmoktan715@gmail.com
spring.mail.password=gfep juao fspr xted

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

google.client-id=568025625243-3o4gl8k6qmsp7km3gph9864qoh9oiisi.apps.googleusercontent.com

spring.rabbitmq.addresses=amqps://slualthp:EnBYzLBSkPd3kPcltruKRyMiWQT9_wce@warthog.lmq.cloudamqp.com/slualthp
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000