spring.application.name=backend

app.frontend.url=http://localhost:4200

jwt.secret=AfTz6L1nK9sW8mP6rJvXqT7eUc1ZHa0OqWdGM7yVn2FjP4lXkS2rZb1cN4hW5e9A
jwt.token.access.expire.time=1800000
jwt.token.refresh.expire.time=604800000

spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.vfhsxodajschliujtvdo
spring.datasource.password=N6XXOPrVM6i9KgnD

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=aashishmoktan715@gmail.com
spring.mail.password=gfep juao fspr xted

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

google.client-id=568025625243-3o4gl8k6qmsp7km3gph9864qoh9oiisi.apps.googleusercontent.com